//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_Lists
    {
        public int RecId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GrpId { get; set; }
        public string IdStr { get; set; }
        public string Audit { get; set; }
    }
}
