//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_Group
    {
        public lsttbl_Group()
        {
            this.lsttbl_Item = new HashSet<lsttbl_Item>();
        }
    
        public int GrpId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Descrip { get; set; }
    
        public virtual lsttbl_Type lsttbl_Type { get; set; }
        public virtual ICollection<lsttbl_Item> lsttbl_Item { get; set; }
    }
}
