//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dukeofaustinEntities : DbContext
    {
        public dukeofaustinEntities()
            : base("name=dukeofaustinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<lsttbl_Group> lsttbl_Group { get; set; }
        public DbSet<lsttbl_Item> lsttbl_Item { get; set; }
        public DbSet<lsttbl_Lists> lsttbl_Lists { get; set; }
        public DbSet<lsttbl_Type> lsttbl_Type { get; set; }
        public DbSet<SiteAppUser> SiteAppUsers { get; set; }
    }
}
