//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAppUser
    {
        public int UserId { get; set; }
        public string UniqId { get; set; }
        public string AppVer { get; set; }
        public string Email { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Secure { get; set; }
        public string Custom { get; set; }
        public string Audit { get; set; }
    }
}
